/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sudokusolver;

import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Rodrigo
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        smallBoard1 = new javax.swing.JLayeredPane();
        cell1 = new javax.swing.JTextField();
        cell2 = new javax.swing.JTextField();
        cell3 = new javax.swing.JTextField();
        cell10 = new javax.swing.JTextField();
        cell11 = new javax.swing.JTextField();
        cell12 = new javax.swing.JTextField();
        cell19 = new javax.swing.JTextField();
        cell20 = new javax.swing.JTextField();
        cell21 = new javax.swing.JTextField();
        smallBoard2 = new javax.swing.JLayeredPane();
        cell4 = new javax.swing.JTextField();
        cell5 = new javax.swing.JTextField();
        cell6 = new javax.swing.JTextField();
        cell15 = new javax.swing.JTextField();
        cell14 = new javax.swing.JTextField();
        cell13 = new javax.swing.JTextField();
        cell22 = new javax.swing.JTextField();
        cell23 = new javax.swing.JTextField();
        cell24 = new javax.swing.JTextField();
        smallBoard3 = new javax.swing.JLayeredPane();
        cell7 = new javax.swing.JTextField();
        cell8 = new javax.swing.JTextField();
        cell9 = new javax.swing.JTextField();
        cell18 = new javax.swing.JTextField();
        cell17 = new javax.swing.JTextField();
        cell16 = new javax.swing.JTextField();
        cell25 = new javax.swing.JTextField();
        cell26 = new javax.swing.JTextField();
        cell27 = new javax.swing.JTextField();
        smallBoard4 = new javax.swing.JLayeredPane();
        cell28 = new javax.swing.JTextField();
        cell29 = new javax.swing.JTextField();
        cell30 = new javax.swing.JTextField();
        cell39 = new javax.swing.JTextField();
        cell38 = new javax.swing.JTextField();
        cell37 = new javax.swing.JTextField();
        cell46 = new javax.swing.JTextField();
        cell47 = new javax.swing.JTextField();
        cell48 = new javax.swing.JTextField();
        smallBoard5 = new javax.swing.JLayeredPane();
        cell31 = new javax.swing.JTextField();
        cell32 = new javax.swing.JTextField();
        cell33 = new javax.swing.JTextField();
        cell42 = new javax.swing.JTextField();
        cell41 = new javax.swing.JTextField();
        cell40 = new javax.swing.JTextField();
        cell49 = new javax.swing.JTextField();
        cell50 = new javax.swing.JTextField();
        cell51 = new javax.swing.JTextField();
        smallBoard6 = new javax.swing.JLayeredPane();
        cell34 = new javax.swing.JTextField();
        cell35 = new javax.swing.JTextField();
        cell36 = new javax.swing.JTextField();
        cell45 = new javax.swing.JTextField();
        cell44 = new javax.swing.JTextField();
        cell43 = new javax.swing.JTextField();
        cell52 = new javax.swing.JTextField();
        cell53 = new javax.swing.JTextField();
        cell54 = new javax.swing.JTextField();
        smallBoard7 = new javax.swing.JLayeredPane();
        cell55 = new javax.swing.JTextField();
        cell56 = new javax.swing.JTextField();
        cell57 = new javax.swing.JTextField();
        cell66 = new javax.swing.JTextField();
        cell65 = new javax.swing.JTextField();
        cell64 = new javax.swing.JTextField();
        cell73 = new javax.swing.JTextField();
        cell74 = new javax.swing.JTextField();
        cell75 = new javax.swing.JTextField();
        smallBoard8 = new javax.swing.JLayeredPane();
        cell58 = new javax.swing.JTextField();
        cell59 = new javax.swing.JTextField();
        cell60 = new javax.swing.JTextField();
        cell69 = new javax.swing.JTextField();
        cell68 = new javax.swing.JTextField();
        cell67 = new javax.swing.JTextField();
        cell76 = new javax.swing.JTextField();
        cell77 = new javax.swing.JTextField();
        cell78 = new javax.swing.JTextField();
        smallBoard9 = new javax.swing.JLayeredPane();
        cell61 = new javax.swing.JTextField();
        cell62 = new javax.swing.JTextField();
        cell63 = new javax.swing.JTextField();
        cell72 = new javax.swing.JTextField();
        cell71 = new javax.swing.JTextField();
        cell70 = new javax.swing.JTextField();
        cell79 = new javax.swing.JTextField();
        cell80 = new javax.swing.JTextField();
        cell81 = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        solveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Classic Sudoku Solver");
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        smallBoard1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        cell2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        smallBoard1.setLayer(cell1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard1.setLayer(cell2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard1.setLayer(cell3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard1.setLayer(cell10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard1.setLayer(cell11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard1.setLayer(cell12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard1.setLayer(cell19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard1.setLayer(cell20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard1.setLayer(cell21, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout smallBoard1Layout = new javax.swing.GroupLayout(smallBoard1);
        smallBoard1.setLayout(smallBoard1Layout);
        smallBoard1Layout.setHorizontalGroup(
            smallBoard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smallBoard1Layout.createSequentialGroup()
                .addGroup(smallBoard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(smallBoard1Layout.createSequentialGroup()
                        .addComponent(cell19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(smallBoard1Layout.createSequentialGroup()
                        .addComponent(cell10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(smallBoard1Layout.createSequentialGroup()
                        .addComponent(cell1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        smallBoard1Layout.setVerticalGroup(
            smallBoard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smallBoard1Layout.createSequentialGroup()
                .addGroup(smallBoard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(smallBoard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(smallBoard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell21, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        smallBoard2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        smallBoard2.setLayer(cell4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard2.setLayer(cell5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard2.setLayer(cell6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard2.setLayer(cell15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard2.setLayer(cell14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard2.setLayer(cell13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard2.setLayer(cell22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard2.setLayer(cell23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard2.setLayer(cell24, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout smallBoard2Layout = new javax.swing.GroupLayout(smallBoard2);
        smallBoard2.setLayout(smallBoard2Layout);
        smallBoard2Layout.setHorizontalGroup(
            smallBoard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, smallBoard2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(smallBoard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(smallBoard2Layout.createSequentialGroup()
                        .addComponent(cell22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(smallBoard2Layout.createSequentialGroup()
                        .addComponent(cell13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(smallBoard2Layout.createSequentialGroup()
                        .addComponent(cell4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        smallBoard2Layout.setVerticalGroup(
            smallBoard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, smallBoard2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(smallBoard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(smallBoard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(smallBoard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell23, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell24, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        smallBoard3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        smallBoard3.setLayer(cell7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard3.setLayer(cell8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard3.setLayer(cell9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard3.setLayer(cell18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard3.setLayer(cell17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard3.setLayer(cell16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard3.setLayer(cell25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard3.setLayer(cell26, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard3.setLayer(cell27, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout smallBoard3Layout = new javax.swing.GroupLayout(smallBoard3);
        smallBoard3.setLayout(smallBoard3Layout);
        smallBoard3Layout.setHorizontalGroup(
            smallBoard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(smallBoard3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(smallBoard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(smallBoard3Layout.createSequentialGroup()
                        .addComponent(cell25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(smallBoard3Layout.createSequentialGroup()
                        .addComponent(cell16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(smallBoard3Layout.createSequentialGroup()
                        .addComponent(cell7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        smallBoard3Layout.setVerticalGroup(
            smallBoard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, smallBoard3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(smallBoard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(smallBoard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(smallBoard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell25, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell26, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell27, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
        );

        smallBoard4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell39.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell47.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell48.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        smallBoard4.setLayer(cell28, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard4.setLayer(cell29, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard4.setLayer(cell30, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard4.setLayer(cell39, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard4.setLayer(cell38, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard4.setLayer(cell37, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard4.setLayer(cell46, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard4.setLayer(cell47, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard4.setLayer(cell48, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout smallBoard4Layout = new javax.swing.GroupLayout(smallBoard4);
        smallBoard4.setLayout(smallBoard4Layout);
        smallBoard4Layout.setHorizontalGroup(
            smallBoard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, smallBoard4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(smallBoard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(smallBoard4Layout.createSequentialGroup()
                        .addComponent(cell46, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell47, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell48, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(smallBoard4Layout.createSequentialGroup()
                        .addComponent(cell37, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell38, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell39, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(smallBoard4Layout.createSequentialGroup()
                        .addComponent(cell28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        smallBoard4Layout.setVerticalGroup(
            smallBoard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, smallBoard4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(smallBoard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell28, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell29, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell30, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(smallBoard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell37, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell38, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell39, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(smallBoard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell46, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell47, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell48, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        smallBoard5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell49.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell51.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        smallBoard5.setLayer(cell31, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard5.setLayer(cell32, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard5.setLayer(cell33, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard5.setLayer(cell42, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard5.setLayer(cell41, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard5.setLayer(cell40, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard5.setLayer(cell49, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard5.setLayer(cell50, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard5.setLayer(cell51, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout smallBoard5Layout = new javax.swing.GroupLayout(smallBoard5);
        smallBoard5.setLayout(smallBoard5Layout);
        smallBoard5Layout.setHorizontalGroup(
            smallBoard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, smallBoard5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(smallBoard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(smallBoard5Layout.createSequentialGroup()
                        .addComponent(cell49, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell50, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell51, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(smallBoard5Layout.createSequentialGroup()
                        .addComponent(cell40, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell41, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(smallBoard5Layout.createSequentialGroup()
                        .addComponent(cell31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        smallBoard5Layout.setVerticalGroup(
            smallBoard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, smallBoard5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(smallBoard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell31, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell32, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell33, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(smallBoard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell40, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell41, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell42, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(smallBoard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell49, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell50, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell51, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        smallBoard6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell52.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell53.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell54.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        smallBoard6.setLayer(cell34, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard6.setLayer(cell35, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard6.setLayer(cell36, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard6.setLayer(cell45, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard6.setLayer(cell44, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard6.setLayer(cell43, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard6.setLayer(cell52, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard6.setLayer(cell53, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard6.setLayer(cell54, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout smallBoard6Layout = new javax.swing.GroupLayout(smallBoard6);
        smallBoard6.setLayout(smallBoard6Layout);
        smallBoard6Layout.setHorizontalGroup(
            smallBoard6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, smallBoard6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(smallBoard6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(smallBoard6Layout.createSequentialGroup()
                        .addComponent(cell52, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell53, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell54, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(smallBoard6Layout.createSequentialGroup()
                        .addComponent(cell43, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell44, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell45, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(smallBoard6Layout.createSequentialGroup()
                        .addComponent(cell34, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell35, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        smallBoard6Layout.setVerticalGroup(
            smallBoard6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, smallBoard6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(smallBoard6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell34, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell35, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell36, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(smallBoard6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell43, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell44, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell45, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(smallBoard6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell52, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell53, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell54, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        smallBoard7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell55.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell56.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell57.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell66.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell66.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell65.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell65.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell64.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell64.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell73.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell73.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell74.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell74.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell75.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell75.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        smallBoard7.setLayer(cell55, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard7.setLayer(cell56, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard7.setLayer(cell57, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard7.setLayer(cell66, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard7.setLayer(cell65, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard7.setLayer(cell64, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard7.setLayer(cell73, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard7.setLayer(cell74, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard7.setLayer(cell75, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout smallBoard7Layout = new javax.swing.GroupLayout(smallBoard7);
        smallBoard7.setLayout(smallBoard7Layout);
        smallBoard7Layout.setHorizontalGroup(
            smallBoard7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, smallBoard7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(smallBoard7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(smallBoard7Layout.createSequentialGroup()
                        .addComponent(cell73, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell74, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell75, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(smallBoard7Layout.createSequentialGroup()
                        .addComponent(cell64, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell65, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell66, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(smallBoard7Layout.createSequentialGroup()
                        .addComponent(cell55, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell56, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell57, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        smallBoard7Layout.setVerticalGroup(
            smallBoard7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, smallBoard7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(smallBoard7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell55, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell56, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell57, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(smallBoard7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell64, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell65, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell66, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(smallBoard7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell73, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell74, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell75, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        smallBoard8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell58.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell58.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell59.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell59.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell60.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell69.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell69.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell68.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell68.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell67.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell67.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell76.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell76.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell77.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell77.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell78.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell78.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        smallBoard8.setLayer(cell58, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard8.setLayer(cell59, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard8.setLayer(cell60, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard8.setLayer(cell69, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard8.setLayer(cell68, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard8.setLayer(cell67, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard8.setLayer(cell76, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard8.setLayer(cell77, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard8.setLayer(cell78, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout smallBoard8Layout = new javax.swing.GroupLayout(smallBoard8);
        smallBoard8.setLayout(smallBoard8Layout);
        smallBoard8Layout.setHorizontalGroup(
            smallBoard8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, smallBoard8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(smallBoard8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(smallBoard8Layout.createSequentialGroup()
                        .addComponent(cell76, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell77, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell78, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(smallBoard8Layout.createSequentialGroup()
                        .addComponent(cell67, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell68, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell69, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(smallBoard8Layout.createSequentialGroup()
                        .addComponent(cell58, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell59, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell60, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        smallBoard8Layout.setVerticalGroup(
            smallBoard8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, smallBoard8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(smallBoard8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell58, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell59, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell60, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(smallBoard8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell67, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell68, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell69, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(smallBoard8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell76, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell77, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell78, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        smallBoard9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell61.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell62.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell62.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell63.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell63.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell72.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell72.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell71.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell71.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell70.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell70.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell79.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell79.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell80.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell80.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cell81.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell81.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        smallBoard9.setLayer(cell61, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard9.setLayer(cell62, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard9.setLayer(cell63, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard9.setLayer(cell72, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard9.setLayer(cell71, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard9.setLayer(cell70, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard9.setLayer(cell79, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard9.setLayer(cell80, javax.swing.JLayeredPane.DEFAULT_LAYER);
        smallBoard9.setLayer(cell81, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout smallBoard9Layout = new javax.swing.GroupLayout(smallBoard9);
        smallBoard9.setLayout(smallBoard9Layout);
        smallBoard9Layout.setHorizontalGroup(
            smallBoard9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, smallBoard9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(smallBoard9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(smallBoard9Layout.createSequentialGroup()
                        .addComponent(cell79, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell80, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell81, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(smallBoard9Layout.createSequentialGroup()
                        .addComponent(cell70, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell71, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell72, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(smallBoard9Layout.createSequentialGroup()
                        .addComponent(cell61, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell62, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cell63, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        smallBoard9Layout.setVerticalGroup(
            smallBoard9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, smallBoard9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(smallBoard9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell61, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell62, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell63, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(smallBoard9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell70, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell71, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell72, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(smallBoard9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell79, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell80, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cell81, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(smallBoard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(smallBoard4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(smallBoard5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(smallBoard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(smallBoard3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(smallBoard6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(smallBoard7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(smallBoard8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(smallBoard9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(smallBoard2)
                    .addComponent(smallBoard1)
                    .addComponent(smallBoard3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(smallBoard4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smallBoard5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smallBoard6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(smallBoard7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smallBoard8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smallBoard9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        solveButton.setText("Solve");
        solveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(solveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearButton)
                    .addComponent(solveButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void solveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solveButtonActionPerformed
        // Store cells in an array, so it's easier to work with it later.
        JTextField cells[] = {cell1, cell2, cell3, cell4, cell5, cell6, cell7,
            cell8, cell9, cell10, cell11, cell12, cell13, cell14, cell15, cell16,
            cell17, cell18, cell19, cell20, cell21, cell22, cell23, cell24, cell25,
            cell26, cell27, cell28, cell29, cell30, cell31, cell32, cell33, cell34,
            cell35, cell36, cell37, cell38, cell39, cell40, cell41, cell42, cell43,
            cell44, cell45, cell46, cell47, cell48, cell49, cell50, cell51, cell52,
            cell53, cell54, cell55, cell56, cell57, cell58, cell59, cell60, cell61,
            cell62, cell63, cell64, cell65, cell66, cell67, cell68, cell69, cell70,
            cell71, cell72, cell73, cell74, cell75, cell76, cell77, cell78, cell79,
            cell80, cell81};

        int cellsCounter = 0;
        int[][] board = new int[9][9];

        // Put all the inserted values into the board variable.
        for (int i = 0; i < 9; i++) { // Lines
            for (int j = 0; j < 9; j++) { // Columns
                switch (cells[cellsCounter].getText().trim()) {
                    case "1":
                        board[i][j] = 1;
                        break;
                    case "2":
                        board[i][j] = 2;
                        break;
                    case "3":
                        board[i][j] = 3;
                        break;
                    case "4":
                        board[i][j] = 4;
                        break;
                    case "5":
                        board[i][j] = 5;
                        break;
                    case "6":
                        board[i][j] = 6;
                        break;
                    case "7":
                        board[i][j] = 7;
                        break;
                    case "8":
                        board[i][j] = 8;
                        break;
                    case "9":
                        board[i][j] = 9;
                        break;
                    case "":
                        board[i][j] = 0;
                        break;
                    default:
                        // Unallowed value inserted, do not allow.
                        JOptionPane.showMessageDialog(null, "The only allowed "
                                + "values are 1, 2, 3, 4, 5, 6, 7, 8, 9.\nBut it "
                                + "was inserted " + cells[cellsCounter].getText()
                                + " instead.", "Wrong value inserted", JOptionPane.ERROR_MESSAGE);
                        return;
                }
                cellsCounter++;
            }
        }

        // Verify if the board wasn't left totally blank.
        boolean isItBlank = true; // Consider that the board is entirely blank.
        for (int i = 0; i < 9; i++) {
            for (int j = 0; j < 9; j++) {
                if (board[i][j] != 0) {
                    // It isn't totally blank.
                    isItBlank = false;
                    break; // Quit insider for.
                }
            }
            if (!isItBlank) {
                break; // Quit outter for.
            }
        }

        if (isItBlank) {
            // The board is entirely blank, do not allow.
            JOptionPane.showMessageDialog(null, "The board can't be left all blank.\n"
                    + "Please, insert at least a number first.", "Blank board", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Start Genetic Algorithm.
        // Set initial parameters of the algorithm.
        Algorithm.setCrossoverRate(0.3);
        Algorithm.setMutationRate(0.5);

        boolean elitism = true;

        int populationSize = 50;
        int maxNumGenerations = 5000; // Maximum number of generations.

        // Initial random population.
        Population population = new Population(populationSize, board);

        boolean hasSolution = false; // Variable to verify if solution was found.

        int currentGeneration = 1;

        // While it doesn't have a solution or hadn't achieved maximum number of generations.
        while (!(hasSolution) && (currentGeneration < maxNumGenerations)) {
            // Creates a new population to substitute the initial random population.
            population = new Population(Algorithm.newGeneration(population, elitism));

            System.out.println("Generation: " + currentGeneration
                    + " | Fitness: " + population.getBestChromosome().getFitness());

            // Verify if any of the chromosomes is the solution (fitness = 0).
            if (population.getBestChromosome().getFitness() == 0) {
                // It has the solution.
                hasSolution = true;
            }

            currentGeneration++;
        }

        // Print on the board.
        int cellCount = 0;
        for (int i = 0; i < 9; i++) {
            for (int j = 0; j < 9; j++) {
                cells[cellCount].setText(Integer.
                        toString(population.getBestChromosome().getGenes()[i][j]));
                cellCount++;
            }
        }
    }//GEN-LAST:event_solveButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // Store cells in an array, so it's easier to work with it later.
        JTextField cells[] = {cell1, cell2, cell3, cell4, cell5, cell6, cell7,
            cell8, cell9, cell10, cell11, cell12, cell13, cell14, cell15, cell16,
            cell17, cell18, cell19, cell20, cell21, cell22, cell23, cell24, cell25,
            cell26, cell27, cell28, cell29, cell30, cell31, cell32, cell33, cell34,
            cell35, cell36, cell37, cell38, cell39, cell40, cell41, cell42, cell43,
            cell44, cell45, cell46, cell47, cell48, cell49, cell50, cell51, cell52,
            cell53, cell54, cell55, cell56, cell57, cell58, cell59, cell60, cell61,
            cell62, cell63, cell64, cell65, cell66, cell67, cell68, cell69, cell70,
            cell71, cell72, cell73, cell74, cell75, cell76, cell77, cell78, cell79,
            cell80, cell81};

        // Clear the entire board.
        for (JTextField clearTextField : cells) {
            clearTextField.setText("");
        }
    }//GEN-LAST:event_clearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cell1;
    private javax.swing.JTextField cell10;
    private javax.swing.JTextField cell11;
    private javax.swing.JTextField cell12;
    private javax.swing.JTextField cell13;
    private javax.swing.JTextField cell14;
    private javax.swing.JTextField cell15;
    private javax.swing.JTextField cell16;
    private javax.swing.JTextField cell17;
    private javax.swing.JTextField cell18;
    private javax.swing.JTextField cell19;
    private javax.swing.JTextField cell2;
    private javax.swing.JTextField cell20;
    private javax.swing.JTextField cell21;
    private javax.swing.JTextField cell22;
    private javax.swing.JTextField cell23;
    private javax.swing.JTextField cell24;
    private javax.swing.JTextField cell25;
    private javax.swing.JTextField cell26;
    private javax.swing.JTextField cell27;
    private javax.swing.JTextField cell28;
    private javax.swing.JTextField cell29;
    private javax.swing.JTextField cell3;
    private javax.swing.JTextField cell30;
    private javax.swing.JTextField cell31;
    private javax.swing.JTextField cell32;
    private javax.swing.JTextField cell33;
    private javax.swing.JTextField cell34;
    private javax.swing.JTextField cell35;
    private javax.swing.JTextField cell36;
    private javax.swing.JTextField cell37;
    private javax.swing.JTextField cell38;
    private javax.swing.JTextField cell39;
    private javax.swing.JTextField cell4;
    private javax.swing.JTextField cell40;
    private javax.swing.JTextField cell41;
    private javax.swing.JTextField cell42;
    private javax.swing.JTextField cell43;
    private javax.swing.JTextField cell44;
    private javax.swing.JTextField cell45;
    private javax.swing.JTextField cell46;
    private javax.swing.JTextField cell47;
    private javax.swing.JTextField cell48;
    private javax.swing.JTextField cell49;
    private javax.swing.JTextField cell5;
    private javax.swing.JTextField cell50;
    private javax.swing.JTextField cell51;
    private javax.swing.JTextField cell52;
    private javax.swing.JTextField cell53;
    private javax.swing.JTextField cell54;
    private javax.swing.JTextField cell55;
    private javax.swing.JTextField cell56;
    private javax.swing.JTextField cell57;
    private javax.swing.JTextField cell58;
    private javax.swing.JTextField cell59;
    private javax.swing.JTextField cell6;
    private javax.swing.JTextField cell60;
    private javax.swing.JTextField cell61;
    private javax.swing.JTextField cell62;
    private javax.swing.JTextField cell63;
    private javax.swing.JTextField cell64;
    private javax.swing.JTextField cell65;
    private javax.swing.JTextField cell66;
    private javax.swing.JTextField cell67;
    private javax.swing.JTextField cell68;
    private javax.swing.JTextField cell69;
    private javax.swing.JTextField cell7;
    private javax.swing.JTextField cell70;
    private javax.swing.JTextField cell71;
    private javax.swing.JTextField cell72;
    private javax.swing.JTextField cell73;
    private javax.swing.JTextField cell74;
    private javax.swing.JTextField cell75;
    private javax.swing.JTextField cell76;
    private javax.swing.JTextField cell77;
    private javax.swing.JTextField cell78;
    private javax.swing.JTextField cell79;
    private javax.swing.JTextField cell8;
    private javax.swing.JTextField cell80;
    private javax.swing.JTextField cell81;
    private javax.swing.JTextField cell9;
    private javax.swing.JButton clearButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLayeredPane smallBoard1;
    private javax.swing.JLayeredPane smallBoard2;
    private javax.swing.JLayeredPane smallBoard3;
    private javax.swing.JLayeredPane smallBoard4;
    private javax.swing.JLayeredPane smallBoard5;
    private javax.swing.JLayeredPane smallBoard6;
    private javax.swing.JLayeredPane smallBoard7;
    private javax.swing.JLayeredPane smallBoard8;
    private javax.swing.JLayeredPane smallBoard9;
    private javax.swing.JButton solveButton;
    // End of variables declaration//GEN-END:variables
}
